INSERT INTO ESP32(Nombre,Valor)  VALUES ('luxometro','135')

CREATE TABLE "ESP32" (
	"id"	INTEGER NOT NULL,
	"Nombre"	TEXT NOT NULL,
	"Valor"	TEXT NOT NULL,
	"Hora"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);